# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Thylens' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Thylens
  pod 'SnapKit',                  '5.0.1'

  target 'ThylensTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ThylensUITests' do
    # Pods for testing
  end

end
